Add a idstore-export CLI tool
liftedinit/many-framework pull request #112
Opened 2022-05-31 23:36 UTC by hansl

2022-06-01 13:34 UTC, fmorency requested changes
Thanks! Some comments!

Can you add a test? We want to make sure this works as expected!

Also, fix CI! The tests don't build at the moment.

2022-06-01 13:34 UTC, fmorency commented on src/idstore-export/src/main.rs
> +            .expect("Could not read see")
seed

2022-06-01 13:34 UTC, fmorency commented on src/many-ledger/src/module.rs
> +                storage.commit_persistent_store().expect("Could not commit");
Not sure I understand why you did this?

2022-06-01 13:34 UTC, fmorency commented on src/many-ledger/src/storage.rs
> +        idstore_seed += 1;
The first seed should be `0`, not `1`

2022-06-01 15:53 UTC, hansl reviewed
Not sure how to make a test, I'll wait for your bats WebAuthn tests before I can make one.

2022-06-21 22:09 UTC, hansl commented
@fmorency Added a test, PTAL.

2022-06-22 13:23 UTC, fmorency requested changes
A small change in testing logic is required. Else LGTM.

2022-06-22 13:23 UTC, fmorency commented on tests/e2e/webauthn.bats
> +    # Continue the test.
You're storing the same identity/key twice. 

To be on the safe side, you should generate and store a new one. Test that you can retrieve the old one as well as the new one using the recall phrase and address.

2022-06-22 16:18 UTC, fmorency approved these changes

2022-06-22 17:04 UTC, merged