Bazel
liftedinit/many-framework pull request #231
Opened 2022-09-06 21:13 UTC by fmorency

MVP.

Bazel files are generated from the `Cargo.toml` manifests.

Uses `rules_rust` v0.10.0.

Supported features
- Build `many-framework`
- Test `many-framework`
- Generate `many-framework` code coverage
- Run fmt
- Run clippy
- Generate rust-analyzer JSON project file

Supported configurations
- build:rustfmt         : Enable rustfmt for all targets
- build:clippy          : Enable clippy for all targets
- run:rust-analyzer     : Generate RA project JSON

**Note**
- I downgraded `ring` to `0.16.20` from `0.17.0-alpha.10` in `ledger` because the alpha version was not building properly with Bazel. We are using `0.16.20` everywhere else anyway.
- There is a workaround for `librocksdb-sys` to unset the C/CXX flags propagated by Bazel. It was causing problems with `bazel coverage`. 

  I feel this is a Bazel issue.

2022-09-08 12:54 UTC, Denommus approved these changes

2022-09-12 20:15 UTC, hansl requested changes
Please create an issue to have many-framework depends on the bazel workspace of many-rs (and/or any other bazel workspaces we control).

2022-09-13 13:22 UTC, fmorency commented
> Please create an issue to have many-framework depends on the bazel workspace of many-rs (and/or any other bazel workspaces we control).

https://github.com/liftedinit/many-framework/issues/235

2022-09-13 21:17 UTC, hansl approved these changes

2022-09-13 21:23 UTC, merged