Migration redesign
liftedinit/many-framework pull request #278
Opened 2022-11-04 20:33 UTC by fmorency

The work is not feature-complete, but you can start the review.

All unit/integration/e2e/resiliency tests are passing.

TODO
- List all migrations from the binary (easy)
- Refactor the Block 9400 migration call in multisig.rs (easy-ish). 
  - I'm not too fond of the current code.
- More cleanup/refactoring
- Tests, tests, tests!!!

2022-11-07 16:54 UTC, hansl commented
I don't understand the UX for IntelliJ PR :/

2022-11-07 16:55 UTC, hansl requested changes
The `'static` change would go a long way in making this easier. Just a first round to get it started.

2022-11-07 16:55 UTC, hansl commented on src/many-ledger/src/migration.rs
> +pub type LedgerMigrations<'a> = BTreeMap<&'a str, Migration<'a, merk::Merk, ManyError>>;
Just make this `'static`. Will save you a lot of references around (and reduce your delta quite a bit). WDYT?

2022-11-07 21:21 UTC, hansl requested changes

2022-11-10 19:29 UTC, hansl approved these changes

2022-11-10 19:55 UTC, fmorency commented on src/many-ledger/src/main.rs
> +            panic!("Migration configuration file is missing migration(s)");
Let's do that in another PR. I'll log an issue.

2022-11-10 20:16 UTC, merged